# Pipeline to force unlock TF state
# Required run time variables:
#
# lock_id - the lock Id locking the state that is to be removed

name: terraform-force-unlock-prod

trigger: none

pool: terraform

variables:
  environment: prod
  keyvaultName: KEYVAULTNAME
  azureSubscription: azure-sub-mgmt

stages:
- template: templates/tf-force-unlock.yml
